Add interface links
tracer-protocol/swaps-client pull request #122
Opened 2021-06-22 01:31 UTC by Steven-Yulong-Yan

### Motivation

Link to external docs

### Changes

- Add a few links to tracer docs

2021-06-22 02:56 UTC, dospore requested changes

2021-06-22 02:56 UTC, dospore commented on components/Trade/Advanced/RightPanel/AccountDetails/index.tsx
> +                {Orders.map((order, index) => {
is this debugging stuff?

2021-06-22 03:14 UTC, Steven-Yulong-Yan commented on components/Trade/Advanced/RightPanel/AccountDetails/index.tsx
> +                {Orders.map((order, index) => {
Shouldn't be here at all sorry

2021-06-22 22:15 UTC, dospore requested changes

2021-06-22 22:15 UTC, dospore commented on components/Trade/Advanced/RightPanel/AccountDetails/index.tsx
> +        width: 100%; /* scrollbar is 5px */
```suggestion
        width: calc(100% - 5px) !important; /* scrollbar is 5px */
```
When the table has entries that scroll, without this then the head columns dont align with the table columns

2021-06-23 00:40 UTC, dospore approved these changes

2021-06-23 00:40 UTC, merged